export const UPDATE_APP_STATUS = 'update app status'
export const UPDATE_ROOM_NUMBER = 'update room number'
export const UPDATE_ROOM_NAME = 'update room name'
export const UPDATE_TEAM_ID = 'update the team id'
export const UPDATE_TEAM_NAME = 'update the team\'s name'
export const UPDATE_LOADING_MESSAGE = 'update loading message'

export const UPDATE_ROOM_PASSWORD = 'update room password'
export const APPROVE_TEAM = 'approve team name'
export const DENY_TEAM = 'deny team name'
export const ADD_TEAM = 'add team to pending teams'
export const CLEAR_TEAMS = 'clear all teams'
export const SET_ANSWERS = 'set pickable answers'

export const UPDATE_FETCHING = 'update if the application is fetching'
export const UPDATE_FETCHING_RESULT = 'update the result of the fetch (success/error)'
export const UPDATE_FETCHING_MESSAGE = 'update the result message'

export const SET_PICKABLE_CATS = 'Set categories the quizmaster can choose from'
export const ADD_CAT = 'Add category to current round'
export const DEL_CAT = 'Remove category from current round'
export const SET_PICKABLE_QUESTIONS = 'Set questions the quizmaster can choose from'
export const SET_QUESTION = 'Set current question (id / text)'
export const SET_QUESTION_NR = 'Set current question no.'
export const SET_ROUND = 'Set current round number'
export const SET_ANSWER = 'Set team\'s answer to current question'